name: Untenshi
version: 1.11.11
main: me.fiveave.untenshi.main
api-version: 1.15
description: Untenshi Plugin
author: 5_AvenueLocal
depend: [ Train_Carts ]
commands:
  uts:
    description: Untenshi Main Commands
    usage: /uts <mode> <value>
  utssignal:
    description: Untenshi Signal Commands (for Command Block)
    usage: /utssignal <x> <y> <z> <mode> <signal> <speed>
  utslogger:
    description: Untenshi Logger
    usage: /utslogger <vehicle_name>
  utsdebug:
    description: Untenshi Debugger
    usage: /utsdebug <vehicle_name> <get/set> <variable>
  utssigntool:
    description: Untenshi Sign Tool
    usage: /utssigntool <getsign/setdir/setsign> <dir>
permissions:
  uts.*:
    description: All Untenshi Perms
    children:
      uts.main: true
      uts.freemode: true
      uts.reload: true
      uts.sign: true
      uts.pa: true
      uts.ato: true
      uts.debug: true
      uts.signtool: true
    default: op
  uts.main:
    description: Allow Untenshi usage (basic perm)
    default: op
  uts.freemode:
    description: Allow freemode change
    default: op
  uts.reload:
    description: Allow config reload
    default: op
  uts.sign:
    description: Allow set sign
    default: op
  uts.pa:
    description: Allow use PA
    default: op
  uts.ato:
    description: Allow usage of ATO
    default: op
  uts.debug:
    description: Allow usage of debug mode
    default: op
  uts.signtool:
    description: Allow usage of sign tool
    default: op